// Shared reference data for per-game hubs. Business/content data, not styling.
export const GAME_DATA = {
  caesar1: {
    image: './images/caesar1.png', imageCredit: 'Community screenshot — Caesar (1992) © Activision',
    name: 'Caesar', years: '1992', civ: 'Rome', accentVar: 'oklch(97% 0.003 60)', archive: true,
    setting: 'Roman Empire', developer: 'Impressions Games',
    publisher: 'Self-published (Impressions Games); Sierra On-Line acquired the studio in 1995',
    credits: 'David Lester (design) · Simon Bradbury (programming)',
    engineNote: 'Top-down, pre-isometric — predates the shared SG/.555 pipeline entirely. Its own reverse-engineering problem, not a variant of the others. Amiga first (Oct 12, 1992), DOS/Atari ST/Mac in 1993.',
    expansions: null,
    formats: [{ name: 'Caesar assets', status: 'dead', note: 'No public documentation exists for Caesar\'s asset formats.' }],
    projects: [],
    wanted: 'No open-source engine or format documentation exists for Caesar — completely virgin reverse-engineering territory.',
    community: [{ title: 'HeavenGames — City Builders Forums', url: 'https://caesar3.heavengames.com/cgi-bin/forums/index.cgi', category: 'Forums', status: 'active', note: 'Shared forums covering the whole series, including Caesar.' }],
  },
  caesar2: {
    image: './images/caesar2.png', imageCredit: 'Community screenshot — Caesar II (1995) © Activision',
    name: 'Caesar II', years: '1995', civ: 'Rome', accentVar: 'oklch(97% 0.003 60)', archive: true,
    setting: 'Roman Empire', developer: 'Impressions Games', publisher: 'Sierra On-Line',
    credits: 'David Lester (design) · Simon Bradbury (programming) · Chris Beatrice (art)',
    engineNote: 'Transitional generation between Caesar and Caesar III — still no open documentation of its asset formats.',
    expansions: null,
    formats: [{ name: 'Caesar II assets', status: 'dead', note: 'No public documentation exists for Caesar II\'s asset formats.' }],
    projects: [],
    wanted: 'No open-source engine or format documentation exists for Caesar II either.',
    community: [{ title: 'HeavenGames — City Builders Forums', url: 'https://caesar3.heavengames.com/cgi-bin/forums/index.cgi', category: 'Forums', status: 'active', note: 'Shared forums covering the whole series, including Caesar II.' }],
  },
  caesar3: {
    image: './images/caesar3.jpg', imageCredit: 'Community screenshot — Caesar III (1998) © Activision',
    name: 'Caesar III', years: '1998', civ: 'Rome', accentVar: 'oklch(97% 0.003 60)', archive: false,
    setting: 'Roman Empire', developer: 'Impressions Games', publisher: 'Sierra Studios',
    credits: null,
    engineNote: 'The archetype. Isometric 2D sprites on .sg2 + .555 assets, .map scenarios, .sav saves. The official map editor landed in the v1.1 patch — the engine every later title in this era shares.',
    expansions: null,
    formats: [
      { name: '.sg2 + .555', status: 'active', note: 'Documented — see the citybuilding-tools wiki. SG index: 600B, 300×uint16 group-ID map. Pixel data: 16-bit LE 5-5-5 RGB, 0xF81F transparency key.' },
      { name: '.map', status: 'dormant', note: 'Partial — Julius/Augustus source is the closest thing to a spec.' },
      { name: '.sav', status: 'dormant', note: 'Partial — tacit hex-editing lore on HeavenGames forums.' },
    ],
    projects: [
      { name: 'Julius', lineage: 'Foundational — base of the lineage', language: 'C (SDL2)', status: 'active', saveCompat: '100% — byte-identical goal, saves fully compatible with the original', platforms: 'Windows, Linux, macOS, Android, Vita, Switch', activity: 'First release Nov 2018 · actively maintained', repoUrl: 'https://github.com/bvschaik/julius' },
      { name: 'Augustus', lineage: 'Fork of Julius', language: 'C (SDL2)', status: 'active', saveCompat: 'One-way — loads Julius/C3 saves', platforms: 'Windows, Linux, macOS · browser build', activity: 'Most active dev community · hosts a Discord', repoUrl: 'https://github.com/Keriew/augustus' },
    ],
    wanted: null,
    community: [
      { title: 'HeavenGames — City Builders Forums', url: 'https://caesar3.heavengames.com/cgi-bin/forums/index.cgi', category: 'Forums', status: 'active', note: 'The main hub — news archives back to 2002, downloads, FAQs.' },
      { title: 'Augustus Discord', url: '', category: 'Discord', status: 'active', note: 'Hosted by GamerZakh — the most active live dev/modding community found.' },
      { title: 'caesaralan.co.uk', url: 'https://www.caesaralan.co.uk', category: 'Single-author', status: 'dormant', note: 'Repeatedly cited as the best single-author resource. Still unverified whether it\'s currently live.' },
    ],
  },
  pharaoh: {
    image: './images/pharaoh.jpg', imageCredit: 'Community screenshot — Pharaoh (1999) © Activision',
    name: 'Pharaoh', years: '1999', civ: 'Egypt', accentVar: 'oklch(75% 0.004 60)', archive: false,
    setting: 'Ancient Egypt', developer: 'Impressions Games', publisher: 'Sierra Studios',
    credits: 'Chris Beatrice (design) · Gingerich (programming)',
    engineNote: 'Same engine as Caesar III, moved to Egypt and onto .sg3.',
    expansions: 'Cleopatra (2000) · bundled as Pharaoh Gold (2001)',
    formats: [
      { name: '.sg3 + .555', status: 'active', note: 'Documented — same wiki as Caesar III, plus OpenPharaoh\'s SG3.bt template.' },
      { name: '.map / .sav', status: 'dormant', note: 'Partial, inherited from the Caesar III generation.' },
    ],
    projects: [
      { name: 'Akhenaten', lineage: 'Fork of Ozymandias', language: 'C/C++ (CMake 3.30+)', status: 'active', saveCompat: 'Requires Pharaoh patched to 1.3 + Cleopatra; demo unsupported', platforms: 'Windows 10/11, major Linux distros, macOS (arm64 + x86_64)', activity: 'First commit late 2023 · the currently living Pharaoh project', repoUrl: 'https://github.com/dalerank/Akhenaten' },
      { name: 'Ozymandias (Godot)', lineage: 'Rewrite of the Julius fork in Godot 3.6', language: 'GDScript (Godot 3.6)', status: 'dormant', saveCompat: 'Unconfirmed', platforms: 'Windows, Linux, macOS (Godot export)', activity: 'Dormant since ~Sept 2022', repoUrl: 'https://github.com/Banderi/Ozymandias' },
      { name: 'Ozymandias (Julius fork)', lineage: 'Fork of Julius, targeting Pharaoh', language: 'C (SDL2)', status: 'dormant', saveCompat: 'Inherits the Julius save model — unconfirmed for Pharaoh', platforms: 'Windows, Linux, macOS', activity: 'Superseded by the Godot port', repoUrl: 'https://github.com/Banderi/Ozymandias_Julius' },
      { name: 'OpenPharaoh', lineage: 'Independent — from-scratch .NET/XNA attempt', language: '.NET / Mono + XNA', status: 'dead', saveCompat: 'Not functional as a game engine', platforms: 'Windows (.NET/XNA)', activity: 'No known recent activity — but ships a 010 Editor SG3 template and a C# parser', repoUrl: 'https://github.com/gaddas/OpenPharaoh' },
    ],
    wanted: null,
    community: [
      { title: 'pharaoh.heavengames.com', url: 'https://pharaoh.heavengames.com', category: 'Forums', status: 'active', note: 'Per-game HeavenGames site — news, downloads, FAQ.' },
      { title: 'Impressions Games Wiki (Fandom)', url: 'https://impressionsgames.fandom.com', category: 'Wiki', status: 'active', note: 'Cross-game coverage, uneven and ad-heavy.' },
    ],
  },
  zeus: {
    image: './images/zeus.jpeg', imageCredit: 'Community screenshot — Zeus: Master of Olympus (2000) © Activision',
    name: 'Zeus: Master of Olympus', years: '2000', civ: 'Greece', accentVar: 'oklch(48% 0.004 60)', archive: false,
    setting: 'Ancient Greece', developer: 'Impressions Games', publisher: 'Sierra Studios',
    credits: 'Chris Beatrice (design) · Gingerich (programming)',
    engineNote: 'An engine revamp, not a reskin: global labor pool replaces labor walkers, no forts, elite housing built directly.',
    expansions: 'Poseidon (2001)',
    formats: [
      { name: '.sg3 + .555', status: 'active', note: 'Documented, same lineage as Pharaoh.' },
      { name: '.eng', status: 'dormant', note: 'Partial — eZeus ships a working converter, format never formally written up.' },
    ],
    projects: [
      { name: 'Olympus', lineage: 'Built on eZeus', language: 'C++ (Qt)', status: 'active', saveCompat: 'Same model as eZeus', platforms: 'Windows (packaged builds)', activity: 'Newer packaged releases · 0.1.0-rc.1', repoUrl: 'https://github.com/gitTerebi/Olympus' },
      { name: 'eZeus', lineage: 'Independent — not byte-exact by design', language: 'C++ (Qt)', status: 'dormant', saveCompat: 'N/A — intentional divergences (new walker model, dual-city play)', platforms: 'Windows, Linux (Qt)', activity: 'Base for Olympus · English/Polish only (font glyph limits)', repoUrl: 'https://github.com/MaurycyLiebner/eZeus' },
      { name: 'CityBuilderEngine', lineage: 'Independent — inspired by Zeus, not a reimplementation', language: 'C++14 (Qt5)', status: 'dormant', saveCompat: 'N/A — new engine, not save-compatible', platforms: 'Windows, Linux (Qt5) · server/client split', activity: 'Early stage — map engine only', repoUrl: 'https://github.com/Vinorcola/CityBuilderEngine' },
    ],
    wanted: null,
    community: [
      { title: 'zeus.heavengames.com', url: 'https://zeus.heavengames.com', category: 'Forums', status: 'active', note: 'Per-game HeavenGames site — news, downloads, FAQ.' },
    ],
  },
  emperor: {
    image: './images/emperor.png', imageCredit: 'Community screenshot — Emperor: Rise of the Middle Kingdom (2002) © Activision',
    name: 'Emperor: Rise of the Middle Kingdom', years: '2002', civ: 'China', accentVar: 'oklch(34% 0.004 60)', archive: false,
    setting: 'Ancient China, Xia → Song-Jin (2033 BC–1234 AD)', developer: 'BreakAway Games', publisher: 'Sierra',
    credits: null,
    engineNote: 'Built on the Zeus engine. Last title on the 2D sprite engine, and the first in the series with multiplayer.',
    expansions: null,
    formats: [
      { name: '.sg3 + .555', status: 'active', note: 'Documented, same lineage as Pharaoh/Zeus.' },
      { name: '.eng', status: 'dormant', note: 'Partial, same converter situation as Zeus.' },
    ],
    projects: [],
    wanted: 'No open-source engine reimplementation exists for Emperor — confirmed across two research passes. It shares the Zeus engine generation and .sg3/.555 formats, so an eZeus- or Julius-lineage fork is technically plausible. The most credible open target in the whole archive.',
    community: [
      { title: 'emperor.heavengames.com', url: 'https://emperor.heavengames.com', category: 'Forums', status: 'active', note: 'Notably documents bugs Impressions never fixed before going under.' },
      { title: "Gweilo's Emperor Campaign Compilation", url: '', category: 'Single-author', status: 'dormant', note: 'A maintained collection of community campaigns — worth preserving.' },
    ],
  },
};
